// Going to greeting
-> greeting

=== greeting === 
Booo hooo hooo hooo... Yarrr harrr harrr harrr...

Me ship... s'all in splinters...

Worry not lad, I know ye was just try'na help...

But I fear yer quartermaster might see it a wee bit different...
-> END